### ISSUE TITLE
Bug of statistics for new Tag "windows-10-universal"

### ISSUE THREAD

**Issue by GraceFeng** [Myfreedom614/SOPerformanceTool#1]
New tag "windows-10-universal" has been added to our Stackoverflow Tool, but this tag is not added to the SOPerformaceTool, for example this [Windows 10 UWP app: StreamSocket via mobile broadband](http://stackoverflow.com/questions/35751733/windows-10-uwp-app-streamsocket-via-mobile-broadband) case.

**Comment by Myfreedom614** [comment]
Closed by f2df52c0892ce6400bc2ee131663fde1b9bb30cd
